eaciit/x10

webapps/assets/core/formula.js
webapps/views/formula/default.html

push export table to excel formula page

---

webapps/assets/core/formula.js
webapps/assets/core/ratio-report.js
webapps/views/menusetting/default.html

comit export excel give new colom and fix data not displayed

comit export excel give new colom and fix data not displayed

---

webapps/assets/core/formula.js
webapps/controllers/formulaglossary.go
webapps/views/formulaglossary/default.html
webapps/webext/webext.go

comit change for excel formula and pdf formula glossary

comit change for excel formula and pdf formula glossary

---

webapps/controllers/rtr.go

fix bug ketika melakukan save pada row baru rtr

fix bug ketika melakukan save pada row baru rtr

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/formsandreportlogic.js
webapps/controllers/formsandreportlogic.go
webapps/views/accountdetail/input.html
webapps/views/formsandreportlogic/default.html
webapps/webext/webext.go

comit ui forms and report logic

comit ui forms and report logic

---

webapps/assets/core/formsandreportlogic.js
webapps/controllers/formsandreportlogic.go
webapps/views/formsandreportlogic/default.html

comit change implementation forms and report logic

comit change implementation forms and report logic

---

webapps/assets/core/ratio-input.js
webapps/assets/core/ratio-pdf.js
webapps/assets/core/ratio-report.js
webapps/controllers/ratio.go

fix set value N/A ketika column Balance Sheet Input Not Available

fix set value N/A ketika column Balance Sheet Input Not Available

---

webapps/assets/core/formsandreportlogic.js
webapps/views/formsandreportlogic/default.html

comit loader

---

webapps/assets/core/bank-analysis-additional.js
webapps/controllers/bankanalysis.go
webapps/models/bankanalysis.go
webapps/views/approval/allfield.html
webapps/views/bankanalysis/default.html
webapps/views/financialsnapshot/kanan.html

fix implementasi N/A di approval form dan financial snapshot

fix implementasi N/A di approval form dan financial snapshot

---

webapps/assets/core/internalrtr.js
webapps/assets/core/ratio-input.js

add variabel for view

---

webapps/assets/core/approval-form.js
webapps/assets/core/cibilnew.js
webapps/assets/core/internalrtr.js
webapps/views/approval/allfield.html
webapps/views/datacapturing/cibilgridnew.html
webapps/views/datacapturing/panelcibilnew.html
webapps/views/rtr/internalrtr.html
webapps/views/rtr/topgrid.html

fixing perubahan ui

---

webapps/views/datacapturing/stockanddebt.html

fixing bug refresh select customer berbeda di stock and debt

fixing bug refresh select customer berbeda di stock and debt

---

webapps/assets/core/role-setting.js
webapps/controllers/base.go
webapps/controllers/dashboard.go
webapps/views/dashboard/default.html

fix bug when get add role in role setting

fix bug when get add role in role setting

---

webapps/assets/core/accountdetails-form.js

mas yanda please merge comit error undevined id of dev in account details only

comit error undevined id of dev in account details

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

comit bug on loan detais enable disable other input when ifbackedPo getting false or if existing customer getting false

comit bug on loan detais enable disable other input when ifbackedPo getting false or if existing customer getting false

---

webapps/models/rtr.go
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailforapplicant.html
webapps/views/datacapturing/detailsofpromotersdirectorsguarantors.html
webapps/views/financialsnapshot/default.html
webapps/views/financialsnapshot/kiri.html

lali perubahan e opo ae

---

webapps/assets/core/bank-analysis-additional.js
webapps/controllers/bankanalysis.go

Fix Bank Analysis Confirm Button

---

webapps/assets/core/bank-analysis-additional.js

Fix all decimal & format align on bank analysis

Fix Decimal and Format Align

---

webapps/assets/core/bank-analysis-additional.js

small fix for sanction limit on od details grid

---

consoleapps/x10upload/helpers/extractor.go
consoleapps/x10upload/helpers/filehelper.go

Add Logic to Renaming Uploaded PDF File

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/loanapproval.js
webapps/views/datacapturing/financialinformation.html
webapps/views/datacapturing/stockanddebt.html
webapps/views/financialsnapshot/kanan.html
webapps/views/loanapproval/custbussinesmix.html
webapps/views/loanapproval/finalsanction.html
webapps/views/loanapproval/loandetail.html
webapps/views/loanapproval/loanourstanding.html
webapps/views/loanapproval/paymenttrack.html
webapps/views/loanapproval/promotersbackground.html
webapps/views/ratio/input.html

set align text to the right for number all page

set align text to the right for number all page 

---

webapps/controllers/rtr.go
webapps/views/rtr/bottomgrid.html

perbaiki bug di rtr ketika data kosong

perbaiki bug di rtr ketika data kosong

---

webapps/models/rtr.go

perbaiki cara ambil od/cc

---

webapps/views/rtr/bottomgrid.html

hapus readonly kendodatepicker rtr

hapus readonly kendodatepicker rtr

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/approval-form.js
webapps/assets/core/rating-input.js
webapps/views/approval/accountdetails.html
webapps/views/approval/allfield.html
webapps/views/approval/bankingsnapshot.html
webapps/views/approval/keypolicyparameters.html
webapps/views/approval/overview.html
webapps/views/rating/input.html
webapps/views/ratio/pdf.html

aproval form fix label and arrange ui

aproval form fix label and arrange ui

---

webapps/assets/core/accountdetails-form.js

login date bug fix 

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

fix date login , hover tooltipster, save and confirm

fix date login , hover tooltipster, save and confirm

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

account details hove pd info

---

webapps/assets/core/cibiltransitory.js

1. Add 'Deal Number' column
2. Add 'Report Generated Date' column 
3. Remove Passport Number column
4. Decrease width of CIBIL Score folder
5. Update labels: 'Promotor Name' -> 'Promoter Name', 'Date Of Birth' -> 'Date of Birth', 'Cibil Score' -> 'CIBIL Score'

Edit Grid Column and Naming

---

webapps/assets/core/accountdetails-form.js

get update status when refresh or window refresh save confime and freeze

get update status when refresh or window refresh save confime and freeze 

---

webapps/assets/core/bank-analysis-additional.js

edited bank analisis set date empty can be saved

edited bank analisis set date empty can be saved

---

webapps/assets/core/bank-analysis-additional.js

bank analisis set edit blank with value sedn 1970-01-01T00:00:00Z

bank analisis set edit blank with value sedn 1970-01-01T00:00:00Z

---

webapps/assets/core/bank-analysis-additional.js

rechange logic date using 1970-01-01T00:00:00Z for sanction date

rechange logic date using 1970-01-01T00:00:00Z for sanction date

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html
webapps/views/bankanalysis/default.html

rechange logic date using 1970-01-01T00:00:00Z for sanction date

iki massssssssssudah

---

webapps/views/rtr/bottomgrid.html

	perbaiki small bug rtr

---

webapps/assets/core/bank-analysis-additional.js
webapps/views/bankanalysis/default.html

fix sum calculate on bank analys

	fix sum calculate on bank analys

---

webapps/assets/core/cibilnew.js
webapps/assets/core/credit-score.js
webapps/assets/core/loanapproval.js
webapps/assets/core/loanapprovalcustom.js
webapps/views/approval/accountdetails.html
webapps/views/creditscorecard/form.html
webapps/views/creditscorecard/new.html
webapps/views/loanapproval/default.html

fixing small bug cibil

---

webapps/assets/core/approval-form.js
webapps/assets/core/credit-score.js
webapps/assets/core/loanapproval.js
webapps/views/approval/allfield.html
webapps/views/loanapproval/loanourstanding.html

fix perbaiki bug hari ini

---

webapps/assets/core/layout.js
webapps/assets/core/usersetting.js
webapps/controllers/usersetting.go
webapps/views/_layout.html
webapps/views/usersetting/default.html

comit user edit and change password

comit user edit and change password

---

webapps/assets/core/layout.js

comit hide message when click again show modal

comit hide message when click again show modal

---

webapps/assets/core/ratio-report.js

display layout grid tree list when get resolution less than 1300

display layout grid tree list when get resolution less than 1300

---

webapps/assets/core/approval-form.js
webapps/assets/core/loanapproval.js

remove hours on date format login date on approva form and loan approval

remove hours on date format login date on approva form and loan approval

---

webapps/controllers/customerprofile.go
webapps/models/cibilindividualreport.go
webapps/models/cibilreport.go
webapps/models/customerprofile.go

add fungsi sync when customerprofile confirm

	add fungsi sync when customerprofile confirm

---

webapps/assets/core/approvalcomments.js
webapps/assets/core/loanapproval.js
webapps/assets/core/ratio-report.js
webapps/models/creditanalys.go
webapps/models/dcfinalsanction.go

set blank when IsNullAmout and IsNullROI , credit analisis IsNullAmount null all in aproval-form and loanAproval report

set blank when IsNullAmout and IsNullROI , credit analisis IsNullAmount null all in aproval-form and loanAproval report

---

webapps/assets/core/approvalcomments.js

re comit set blank not fill or not number data approval form

re comit set blank not fill or not number data approval form

---

webapps/assets/core/approvalcomments.js

re comit again approfalcomments.js

re comit again approfalcomments.js

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/app.js
webapps/assets/core/approval-form.js
webapps/assets/core/approvalcomments.js
webapps/assets/core/loanapproval.js
webapps/assets/jquery-toaster/jquery.toaster.js
webapps/views/_layout.html
webapps/views/creditscorecard/new.html

change toast of notification confirm info

change toast of notification confirm info

---

webapps/assets/core/approval-form.js
webapps/views/approval/overview.html
webapps/views/rtr/bottomgrid.html

hide date save , confimed and freeze which is 0001-01-01T00:00:00Z

hide date save , confimed and freeze which is 0001-01-01T00:00:00Z

---

webapps/views/approval/overview.html

reset loan details in overview blank set 0

reset loan details in overview blank set 0

---

webapps/views/sysroles/default.html

add css set fix size modal

---

webapps/assets/core/bank-analysis-additional.js
webapps/controllers/bankanalysis.go

ambil perhitungan summary dari backend

	ambil perhitungan summary dari backend

---

webapps/controllers/bankanalysis.go
webapps/models/bankanalysis.go

fixing bug nan value from golang

fixing bug nan value from golang

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/approval-form.js
webapps/assets/core/loanapproval.js
webapps/views/accountdetail/input.html
webapps/views/approval/allfield.html
webapps/views/approval/comments.html
webapps/views/approval/default.html
webapps/views/loanapproval/companybackground.html

fixing styling on comment financial

	fixing styling on comment financial

---

webapps/assets/core/keypolicynorms.js
webapps/views/formula/keypolicynorms.html

	fixing bug di norm master

---

webapps/views/approval/comments.html

hide comments comments on financials if empty in approval form

hide comments comments on financials if empty in approval form

---

webapps/views/approval/comments.html

recomit when comment financial get empty set blank

recomit when comment financial get empty set blank

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/customerprofileinfo.js
webapps/assets/core/ratio-input.js
webapps/views/accountdetail/input.html
webapps/views/ratio/input.html

comit set distributor mix delete button disabled when confirm

comit set distributor mix delete button disabled when confirm

---

webapps/views/rtr/bottomgrid.html

fix bug on rtr

---

webapps/views/rtr/bottomgrid.html

set disabled delete button inside grid on rtr

set disabled delete button inside grid on rtr

---

webapps/controllers/duediligence.go

	fixing due diligen input

---

webapps/models/rtr.go
webapps/views/rtr/bottomgrid.html

kerja kerja kerja

---

webapps/assets/core/accountdetails-form.js

set lower case when set Distributor nameAD

set lower case when set Distributor nameAD

---

webapps/views/approval/comments.html
webapps/views/loanapproval/companybackground.html

make alignt left comment on  financial in approval form and loan approval report

make alignt left comment on  financial in approval form and loan approval report

---

webapps/views/approval/allfield.html

recomit add alignt left Comments on financials

recomit add alignt left Comments on financials

---

webapps/assets/core/bank-analysis-additional.js
webapps/controllers/bankanalysis.go
webapps/views/loanapproval/loanourstanding.html

fixing loan approval report security bank analys

	fixing loan approval report security bank analys

---

webapps/assets/core/loanapproval.js
webapps/views/loanapproval/loanourstanding.html

	revisi lagi security bank

---

webapps/assets/core/loanapproval.js
webapps/views/loanapproval/loanourstanding.html

	no comment

---

webapps/assets/core/loanapproval.js

fix bug udefined account.NonFundBased.SecurityOfNFB on loan approval report

fix bug udefined account.NonFundBased.SecurityOfNFB on loan approval report

---

webapps/assets/core/loanapproval.js
webapps/views/loanapproval/loanourstanding.html

fixing bug loan approval report bank analys

	fixing bug loan approval report bank analys

---

webapps/assets/core/cibilcompany.js
webapps/controllers/cibilcompany.go
webapps/views/cibilcompany/default.html
webapps/webext/webext.go

comit prepare page for cibil edit company

comit prepare page for cibil edit company

---

webapps/controllers/cibilcompany.go
webapps/models/cibilreport.go
webapps/webext/webext.go

fix add functional cibil company and 	fixing bug and resolv conflict with origin

	fix add functional cibil company and 	fixing bug and resolv conflict with origin

---

webapps/assets/core/cibilcompany.js
webapps/views/cibilcompany/default.html

create page cibil edit company on view

create page cibil edit company on view

---

webapps/assets/core/cibilcompany.js
webapps/controllers/cibilcompany.go
webapps/models/cibilreport.go
webapps/views/cibilcompany/default.html

	fixing rombak company cibil

---

webapps/assets/core/cibilcompany.js
webapps/views/cibilcompany/default.html

cibil company add form profile

cibil company add form profile 

---

webapps/assets/core/cibilcompany.js
webapps/views/cibilcompany/default.html

recomit cibil company set top layout profile and set string all date

recomit cibil company set top layout profile and set string all date

---

webapps/assets/core/cibilnew.js
webapps/views/datacapturing/cibilgridnew.html
webapps/views/datacapturing/entryreportcibilnew.html

fix add fungsi edit di cibil details

fix add fungsi edit di cibil details

---

webapps/controllers/cibilcompany.go
webapps/models/cibilreport.go

comit backend cibil company

---

webapps/assets/core/cibilcompany.js
webapps/views/cibilcompany/default.html

comit cibil company set join cibil draft and report

comit cibil company set join cibil draft and report

---

webapps/assets/core/cibilcompany.js
webapps/views/cibilcompany/default.html

comit add validaition date empty

comit add validaition date empty

---

webapps/assets/core/cibilnew.js
webapps/views/datacapturing/entryreportcibilnew.html

give validation on form

---

webapps/views/cibilcompany/default.html
webapps/views/datacapturing/entryreportcibilnew.html

set form to div prevent reload page

set form to div prevent reload page

---

webapps/assets/core/ratio-report.js

fix bug resolution under 1300 px

fix bug resolution under 1300 px

---

webapps/assets/core/ratio-report.js

add reload scroller

---

webapps/assets/core/ratio-report.js

fix export excel -> wrong selector

fix export excel -> wrong selector

---

webapps/assets/core/rating-input.js
webapps/views/rating/input.html

fix display modal scroller Ratings model master page

fix display modal scroller Ratings model master page

---

webapps/assets/core/cibilnew.js

fix bug doble coma in formattig  current balance

fix bug doble coma in formattig  current balance

---

webapps/assets/core/ratio-report.js
webapps/views/ratio/report.html

set error on swal and empty layout when get error

set error on swal and empty layout when get error

---

webapps/assets/core/cibilnew.js

	fix fill profile after submit

---

webapps/assets/core/cibilnew.js

add validation only on submit

---

webapps/assets/core/cibilnew.js
webapps/views/datacapturing/cibilnew.html

fix change rule enable confirm after submit on multiple report cibil

	fix change rule enable confirm after submit on multiple report cibil

---

webapps/views/datacapturing/entryreportcibilnew.html

change label input on entry in cibil details

change label input on entry in cibil details

---

webapps/views/datacapturing/entryreportcibilnew.html
webapps/views/datacapturing/panelcibildetails.html

change lable state union teritory

change lable state union teritory

---

webapps/assets/core/databrowser-new.js

set scroll as colum selected

---

webapps/assets/core/cibilnew.js
webapps/controllers/cibil.go
webapps/views/datacapturing/entryreportcibilnew.html

	fix add select by filename

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/financialinformation.html

add number type for all amount and set align right

add number type for all amount and set align right

---

webapps/assets/core/customerprofileinfo.js
webapps/models/customerprofile.go
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/financialinformation.html

comit change type data and give number picker to the table fields

comit change type data and give number picker to the table fields

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/financialinformation.html

add other field type of a/c and chang other field to float

add other field type of a/c and chang other field to float

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/financialinformation.html

change type of a/c to string when load

change type of a/c to string when load

---

webapps/views/login/default.html

Minor css fixup for better display.

Fix application login title stretching and alert margin padding.

---

consoleapps/OmnifinMaster/main.go
consoleapps/OmnifinMaster/product.go
consoleapps/OmnifinMaster/scheme.go
consoleapps/OmnifinMaster/transform.go

Transform master data from remote server into MasterAccountDetail

Implement Omnifin master data product and scheme import

---

webapps/assets/core/accountdetails-form.js
webapps/controllers/customerprofile.go
webapps/views/accountdetail/input.html
webapps/views/datacapturing/customerprofileinfo.html

fixing account details enable disable

	fixing account details enable disable

---

webapps/assets/core/internalrtr.js
webapps/controllers/internalrtr.go
webapps/models/internalrtr.go
webapps/views/rtr/internalrtr.html

comit internal rtr get data set confirmed and set freeze

comit internal rtr get data set confirmed and set freeze

---

webapps/views/datacapturing/customerprofileinfo.html

fixing invalid date

---

webapps/assets/core/internalrtr.js
webapps/models/internalrtr.go

set alignt right and set deliquent value in model

set alignt right and set deliquent value in model

---

webapps/assets/core/databrowser-new.js

data browser checking type of string or boolean

data browser checking type of string or boolean

---

webapps/assets/core/detailsofpromotersdirectorsguarantors.js
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailsofpromotersdirectorsguarantors.html

fixing change select guarantor

	fixing change select guarantor

---

webapps/assets/core/internalrtr.js
webapps/views/rtr/internalrtr.html

implement confirm , re enter , freeze, unfreeze and set format loan amount

implement confirm , re enter , freeze, unfreeze and set format loan amount

---

webapps/assets/core/internalrtr.js
webapps/controllers/internalrtr.go

save confirm implementation

---

webapps/assets/core/databrowser-new.js

databrowser checking null on guarantor , promotor dan director

databrowser checking null on guarantor , promotor dan director

---

webapps/assets/core/newdefaultfilter.js
webapps/views/databrowser/filter.html
webapps/views/databrowser/newdefault.html

tidying layout 

---

webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailsofpromotersdirectorsguarantors.html

Disable Guarantor on Customer Application

Disable Guarantor on Customer Application

---

webapps/assets/core/databrowser-new.js
webapps/views/databrowser/newdefault.html

set link more button on grid and remove bottom line on guarantor, promotor , and director

set link more button on grid and remove bottom line on guarantor, promotor , and director

---

webapps/assets/core/databrowser-new.js
webapps/views/databrowser/newdefault.html

set line display on td

---

webapps/assets/core/newdefaultfilter.js
webapps/views/databrowser/filter.html

set filter range

---

webapps/views/datacapturing/customerprofileinfo.html

Change label to Details of Promoters/Directors/Guarantors/Management

 Change label to Details of Promoters/Directors/Guarantors/Management

---

webapps/assets/core/newdefaultfilter.js

fix bug getdatabrowser

---

webapps/assets/core/databrowser-new.js
webapps/assets/core/newdefaultfilter.js
webapps/controllers/accountdetail.go

comit range internal rating value

comit range internal rating value

---

webapps/assets/core/newdefaultfilter.js
webapps/controllers/accountdetail.go

fix bug filter

---

webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailsofpromotersdirectorsguarantors.html

	fixing color multiselect

---

webapps/views/datacapturing/customerprofileinfo.html

fix instrument date

---

webapps/assets/core/newdefaultfilter.js
webapps/controllers/databrowser.go
webapps/views/databrowser/filter.html

This prototype is phase 1 of new databrowser filtering system. Next step is implement form disabling when more specific filter is applied.

Fix databrowser localclient

---

webapps/views/accountdetail/input.html
webapps/views/databrowser/filter.html
webapps/views/databrowser/newdefault.html

fix text and change some lable on data browser

fix text and change some lable on data browser

---

webapps/views/databrowser/filter.html
webapps/views/databrowser/newdefault.html

change color placeholder text to #676767

change color placeholder text to #676767

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

	fixing acount detail

---

webapps/assets/core/newdefaultfilter.js

Remove choose select

---

webapps/assets/core/databrowser-new.js

add new task get grid databrowser

add new task get grid databrowser

---

webapps/assets/core/databrowser-new.js

fix label date and hyperlink

---

webapps/controllers/databrowser.go
webapps/views/databrowser/default.html
webapps/views/databrowser/newdefault.html

Show username on data browser

---

webapps/controllers/databrowser.go
webapps/views/databrowser/default.html
webapps/views/databrowser/newdefault.html

 	Show username on data browser

---

webapps/assets/core/mastersuplier.js
webapps/controllers/mastersuplier.go
webapps/models/mastersuplier.go
webapps/views/mastersuplier/default.html

add new menu master suplier

---

consoleapps/OmnifinMaster/main.go
consoleapps/OmnifinMaster/stakeholdertype.go
consoleapps/OmnifinMaster/transform.go

Please note there is possibility of name duplication.
We remove duplicate name here.

Implement import stakeholder.

---

webapps/assets/core/mastersuplier.js
webapps/controllers/mastersuplier.go

set save implementation

---

webapps/views/mastersuplier/default.html

master suplier html forgot comit

master suplier html forgot comit

---

webapps/assets/core/mastersuplier.js
webapps/controllers/mastersuplier.go
webapps/views/mastersuplier/default.html

comit delete and add

---

webapps/assets/core/mastersuplier.js

set reload datasource grid

---

webapps/assets/css/custom.css

fix height dropdown

---

webapps/assets/core/mastersuplier.js

edit font to uppercase variabel

edit font to uppercase variabel

---

webapps/assets/core/databrowser-new.js

corect speling, change plus position to right, change page to ten row

 	corect speling, change plus position to right, change page to ten row

---

webapps/controllers/mastersuplier.go
webapps/views/mastersuplier/default.html
webapps/webext/webext.go

fix develop sink with masteraccountdetail

fix develop sink with masteraccountdetail

---

webapps/assets/core/internalrtr.js

Show scroll grid on internal rtr

Show scroll grid on internal rtr

---

webapps/assets/core/databrowser-new.js

give space to plus on databrowser name fields

 	give space to plus on databrowser name fields

---

webapps/assets/core/mastersuplier.js
webapps/controllers/mastersuplier.go

fix edit message error on master suplier

	fix edit message error on master suplier

---

webapps/assets/core/internalrtr.js
webapps/views/rtr/internalrtr.html

change position product and schema , scroll

change position product and schema , scroll

---

webapps/assets/core/internalrtr.js
webapps/views/rtr/internalrtr.html

Refix Scroll Internar RtR

---

webapps/assets/core/mastersuplier.js

	fixing master suplier

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailsofpromotersdirectorsguarantors.html

fix change desgnation on CA

---

webapps/controllers/mastersuplier.go

add ordering master suplier

---

webapps/assets/core/databrowser-new.js
webapps/views/databrowser/newdefault.html

Alot of change at data-browser

Alot of change at data-browser

---

webapps/assets/core/databrowser-new.js
webapps/assets/core/newdefaultfilter.js
webapps/views/databrowser/default.html
webapps/views/databrowser/filter.html
webapps/views/databrowser/newdefault.html

Fix filter data browser style

---

webapps/assets/core/databrowser-new.js
webapps/assets/core/internalrtr.js

- Add form name header at the top .refer the Excel file
- Loan Details should show two columns only on the landing screen. Refer Excel file
- Add Internal RTR columns
- add function link populate data from data browser

Data browser

---

webapps/controllers/accountdetail.go

Refactor prototype databrowser filter

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/financialinformation.html
webapps/views/datacapturing/nonrefundableprocessingfeesdetails.html

change format rs. and change instrument type to drop down

change format rs. and change instrument type to drop down

---

webapps/assets/core/loanapproval.js

- page loan approval report at table promoter background add field city, pincode, state in

page loan approval report 

---

webapps/views/datacapturing/financialinformation.html

fix format local amount and delete plus

fix format local amount and delete plus

---

webapps/assets/core/customerprofileinfo.js
webapps/views/datacapturing/customerprofileinfo.html

set datasource grid on string if there empty

set datasource grid on string if there empty

---

webapps/views/datacapturing/financialinformation.html

comit wrong variabel on dropdown

comit wrong variabel on dropdown

---

webapps/views/datacapturing/financialinformation.html

fix bug date picker

---

webapps/views/datacapturing/financialinformation.html

fix bug and set datasource dropdown

fix bug and set datasource dropdown

---

webapps/assets/css/custom.css

change style dropdown

---

webapps/controllers/dealsetup.go
webapps/models/dealsetup.go

- add function get all data deal setup 
- create model deal setup

page deal setup

---

webapps/assets/core/dealsetup-top.js

page deal setup grid

---

webapps/assets/core/dealsetup-bottom.js
webapps/controllers/dealsetup.go
webapps/models/dealsetup.go
webapps/views/dealsetup/bottom.html
webapps/views/dealsetup/default.html

set implement menu deal set up section details

set implement menu deal set up section details

---

webapps/assets/core/dealsetup-bottom.js
webapps/assets/core/dealsetup-top.js
webapps/controllers/dealsetup.go
webapps/views/dealsetup/bottom.html
webapps/views/dealsetup/default.html

comit section details accept , sendback , disbled button

comit section details accept , sendback , disbled button

---

webapps/assets/core/dealsetup-bottom.js

comit fix alert accept and send back

comit fix alert accept and send back

---

webapps/views/dealsetup/bottom.html

fix label ui remove TAN,

---

webapps/assets/core/detailsofpromotersdirectorsguarantors.js
webapps/controllers/customerprofile.go
webapps/helper/helper.go

Resize Img

---

webapps/assets/core/dealsetup-bottom.js
webapps/assets/core/dealsetup-top.js
webapps/views/dealsetup/default.html

comit add pop up current status

comit add pop up current status

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/ratio-input.js
webapps/views/bankanalysis/default.html

fixing some bug on BSI and AD

---

webapps/assets/core/dealsetup-bottom.js
webapps/views/dealsetup/bottom.html

set detail refrence and detail promotor

set detail refrence and detail promotor

---

webapps/views/dealsetup/bottom.html

disabled input

---

webapps/views/bankanalysis/default.html
webapps/views/dealsetup/bottom.html

change label, change color button , change position button deal setup

change label, change color button , change position button deal setup

---

webapps/assets/core/ratio-input.js

- create function disabled true & false  input in all table cell

page balance sheets inputs

---

webapps/assets/core/bank-analysis-additional.js

-  make when click in grid if value 0 make it " "

page banking analysis

---

webapps/assets/core/approval-form.js
webapps/assets/core/approvalcomments.js
webapps/models/creditanalys.go
webapps/views/approval/comments.html
webapps/views/approval/default.html

fix bug comment approval form

---

webapps/assets/core/approvalcomments.js

fix bug freeze

---

webapps/views/rtr/bottomgrid.html
webapps/views/rtr/default.html

change button style exrtr

---

webapps/controllers/approval.go

Update deal set up on aproval form

Update deal set up on aproval form

---

webapps/views/_layout.html
webapps/views/bankanalysis/default.html
webapps/views/rtr/default.html

change style all button in all pages menu

change style all button in all pages menu

---

webapps/controllers/approval.go
webapps/views/approval/comments.html

input type number

---

webapps/assets/core/ratio-input.js

- add function disable / enable when status commited / Re-enter

- page balance sheet input

---

webapps/assets/core/approvalcomments.js

fix bug recomed condition

---

webapps/assets/core/approvalcomments.js
webapps/controllers/approval.go
webapps/models/dcfinalsanction.go
webapps/views/approval/comments.html

fix develop approval form for button approval, reject and cancel

	fix develop approval form for button approval, reject and cancel

---

webapps/views/approval/comments.html

comiyt dfcs amount and ROI type number

comiyt dfcs amount and ROI type number

---

webapps/controllers/approval.go
webapps/views/approval/comments.html

	disable button

---

webapps/assets/core/approvalcomments.js
webapps/controllers/approval.go
webapps/models/creditanalys.go
webapps/views/approval/comments.html

fix develop approval form final sanction

fix develop approval form final sanction

---

webapps/views/approval/comments.html

set text statu and decision date inline

set text statu and decision date inline

---

webapps/assets/core/approvalcomments.js
webapps/views/approval/comments.html

comit label styling DCFS status and decision date

comit label styling DCFS status and decision date

---

webapps/controllers/approval.go

comit golang aproval bug when get empty

comit golang aproval bug when get empty

---

webapps/controllers/approval.go

remove fmt

---

webapps/controllers/approval.go

	fixing bug save

---

webapps/views/approval/comments.html

Change button style on approval form > di Decision Committe tab

Change button style on approval form > di Decision Committe tab

---

webapps/assets/core/approvalcomments.js
webapps/controllers/approval.go

fixing disable button when data empty

fixing disable button when data empty

---

webapps/assets/core/approval-form.js
webapps/assets/core/approvalcomments.js
webapps/controllers/approval.go
webapps/views/accountdetail/input.html

change label AD pd info modal button save to submit

change label AD pd info modal button save to submit

---

webapps/assets/core/approvalcomments.js

final fix bug ca

---

webapps/assets/core/approvalcomments.js
webapps/controllers/approval.go
webapps/views/approval/comments.html
webapps/views/approval/default.html

fixing approval form rule

---

webapps/conf/app.conf
webapps/connection/connection.go
webapps/helper/timer.go
webapps/main.go
webapps/omnifin/omnifin.go

Fetched user data is saved on MasterUser

Implement timely master user fetching

---

webapps/assets/core/approval-form.js
webapps/assets/core/loanapproval.js
webapps/controllers/approval.go

set toast for notification

---

webapps/assets/core/approval-form.js
webapps/controllers/approval.go

add stock and debt function

---

webapps/assets/core/approval-form.js
webapps/controllers/approval.go

add internal RTR fixToast

---

webapps/assets/core/cibilnew.js
webapps/views/datacapturing/cibilnew.html

fix bug cibil details company summary remove NaN

fix bug cibil details company summary remove NaN

---

webapps/assets/core/newuser.js
webapps/controllers/newuser.go
webapps/models/newuser.go
webapps/views/newuser/default.html
webapps/webext/webext.go

create new page new user

---

webapps/assets/core/reallocation.js
webapps/controllers/reallocation.go
webapps/models/accountdetails.go
webapps/views/approval/comments.html
webapps/views/reallocation/default.html
webapps/webext/webext.go

	period develop allocation

---

webapps/assets/core/newuser.js
webapps/controllers/newuser.go
webapps/models/newuser.go
webapps/views/newuser/default.html

add password, set cat role list from sysrole, set "to be assigned" for empty catrole and catstatus

add password, set cat role list from sysrole, set "to be assigned" for empty catrole and catstatus

---

webapps/assets/core/app.js
webapps/assets/core/bank-analysis-additional.js

fix bug warning message on due diligence form

fix bug warning message on due diligence form

---

webapps/assets/core/bank-analysis-additional.js
webapps/views/dealsetup/default.html

Deal Setup refresh when data empty

 	Deal Setup refresh when data empty

---

webapps/views/dealsetup/default.html

remove event on input filter deal setup

remove event on input filter deal setup

---

webapps/assets/core/newuser.js
webapps/views/reallocation/list.html
webapps/views/reallocation/modal.html

Change style and label on reallocation

 Change style and label on reallocation

---

webapps/views/reallocation/default.html
webapps/views/reallocation/modal.html

Change Style Header Reallocation Deal

 	Change Style Header Reallocation Deal

---

webapps/assets/core/reallocation.js
webapps/controllers/reallocation.go
webapps/models/reallocationdeal.go
webapps/views/reallocation/modal.html

	done allocation deal

---

webapps/assets/core/newuser.js
webapps/controllers/newuser.go
webapps/models/newuser.go
webapps/views/newuser/default.html

set role with last update , disabled cat status in implement

set role with last update , disabled cat status in implement

---

webapps/assets/core/newuser.js
webapps/views/newuser/default.html

fix bug switch

---

webapps/assets/core/newuser.js
webapps/controllers/newuser.go

fix bug grid

---

webapps/assets/core/newuser.js

fix data parameter

---

webapps/views/shared/filter.html

Fixing bug on filter all pages

Fixing bug on filter all pages

---

webapps/assets/core/customerprofileinfo.js
webapps/assets/core/dealsetup-bottom.js
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/financialinformation.html
webapps/views/dealsetup/bottom.html

fix hierarchi grid Existing Relationship With X10 Financial Services Limited

fix hierarchi grid Existing Relationship With X10 Financial Services Limited

---

webapps/assets/core/approval-form.js
webapps/assets/core/cibilcompany.js
webapps/assets/core/cibiltransitory.js
webapps/assets/core/menusetting.js
webapps/assets/core/newuser.js
webapps/assets/core/reallocation.js
webapps/controllers/cibilcompany.go
webapps/controllers/cibiltransitory.go
webapps/controllers/menusetting.go
webapps/controllers/newuser.go
webapps/controllers/reallocation.go
webapps/views/approval/comments.html
webapps/views/cibilcompany/default.html
webapps/views/cibiltransitory/default.html
webapps/views/menusetting/default.html
webapps/views/newuser/default.html
webapps/views/reallocation/default.html
webapps/views/reallocation/list.html
webapps/views/rtr/internalrtr.html

give grant cibil company and cibil transitory

give grant cibil company and cibil transitory

---

webapps/assets/core/role-setting.js
webapps/views/databrowser/newdefault.html
webapps/views/sysroles/default.html

give grant databrowser and role page

give grant databrowser and role page

---

webapps/assets/core/dealsetup-top.js
webapps/assets/core/newuser.js
webapps/assets/core/role-setting.js
webapps/controllers/dealsetup.go
webapps/controllers/newuser.go
webapps/views/dealsetup/dealfilter.html
webapps/views/dealsetup/default.html
webapps/views/newuser/default.html
webapps/views/newuser/userfilter.html
webapps/views/sysroles/default.html

filter deal setup and new user

filter deal setup and new user

---

webapps/assets/core/newuser.js

Forgot minor details on user manager

Fixbug for reload grid after saving

---

webapps/assets/core/dealsetup-top.js
webapps/assets/core/role-setting.js
webapps/views/sysroles/default.html

role fix ui 

---

webapps/assets/core/role-setting.js
webapps/controllers/sysroles.go
webapps/views/sysroles/default.html

role add user list

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/dealsetup-bottom.js
webapps/assets/core/dealsetup-top.js
webapps/assets/core/reallocation.js
webapps/views/reallocation/default.html
webapps/views/reallocation/list.html

realocation fix bugs

---

webapps/assets/core/role-setting.js
webapps/controllers/sysroles.go

validation role

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html
webapps/views/datacapturing/customerprofileinfo.html
webapps/views/datacapturing/detailforapplicant.html

give validation on AD and CA

---

webapps/assets/core/accountdetails-form.js

comit bug AD

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/mastersuplier.js
webapps/controllers/mastersuplier.go
webapps/views/accountdetail/input.html
webapps/views/datacapturing/customerprofileinfo.html

Accoun details fixing

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/bank-analysis-additional.js
webapps/views/accountdetail/input.html
webapps/views/datacapturing/financialinformation.html

fix bug isConfirm flag when get confirm for validation

fix bug isConfirm flag when get confirm for validation

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

fix bug delete button when get validate

fix bug delete button when get validate

---

webapps/assets/core/accountdetails-form.js

business start date get blank

---

webapps/assets/core/internalrtr.js

can confirm though it has empty data on irtr

can confirm though it has empty data on irtr

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/loanapproval.js
webapps/views/accountdetail/input.html
webapps/views/loanapproval/default.html

Account details fix bugs and loan apprival loader

Account details fix bugs and loan apprival loader

---

webapps/assets/core/accountdetails-form.js
webapps/views/accountdetail/input.html

fix bug AD in promotor

---

webapps/assets/core/accountdetails-form.js

fix validation for borrower details

fix validation for borrower details

---

webapps/assets/core/approvalcomments.js
webapps/views/loanapproval/finalsanction.html

comit change label date to decision Date and add row status

comit change label date to decision Date and add row status

---

webapps/assets/core/internalrtr.js

if IRTR get blank data and confirm

if IRTR get blank data and confirm

---

webapps/assets/core/databrowser-new.js
webapps/controllers/accountdetail.go
webapps/views/databrowser/newdefault.html

server paging fixbug on collapseble

server paging fixbug on collapseble

---

webapps/assets/core/accountdetails-form.js
webapps/assets/core/layout.js
webapps/views/_layout.html
webapps/views/shared/leftfilter.html

create layout side bars

---

webapps/assets/core/dashboard.js
webapps/controllers/dashboard.go
webapps/views/dashboard/default.html
webapps/views/shared/leftfilter.html

dashboard filter belum bisa binding semua , belum ada struktur data untuk save

dashboard filter belum bisa binding semua , belum ada struktur data untuk save

---

webapps/assets/core/dashboard.js
webapps/assets/core/layout.js
webapps/controllers/dashboard.go
webapps/views/_layout.html
webapps/views/shared/leftfilter.html

fix filter sidebar dashboard

---

webapps/assets/core/dashboard.js
webapps/views/shared/leftfilter.html

filter role binding

---

webapps/assets/core/dashboard-time-tracker.js
webapps/views/dashboard/time_tracker.html

comit deal tracker

---

webapps/assets/core/dashboard-time-tracker.js

remove alert and console.log

---

webapps/assets/core/dashboard-time-tracker.js
webapps/views/dashboard/time_tracker.html

fixing layout

---

webapps/assets/core/dashboard-time-tracker.js
webapps/assets/core/role-setting.js
webapps/views/_layout.html
webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/time_tracker.html
webapps/views/shared/leftfilter.html

time tracker and layouting

---

webapps/assets/core/dashboard-alert-summary.js
webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/time_tracker.html

fix layout

---

webapps/assets/core/dashboard-time-tracker.js
webapps/assets/core/dealsetup-top.js
webapps/assets/core/turnaroundtime.js
webapps/controllers/dashboard.go
webapps/views/dashboard/turnaroundtime.html
webapps/views/dealsetup/dealfilter.html

turnaround and link dealsetup

---

webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/turnaroundtime.html

fix turnaround page

---

webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/turnaroundtime.html

comit change remove glosy color and change  tooltips

comit change remove glosy color and change  tooltips

---

webapps/assets/core/dealprofilmetrics.js
webapps/controllers/dashboard.go
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/turnaroundtime.html

new page dealprofilmetrics

---

webapps/assets/core/dealprofilmetrics.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/turnaroundtime.html

comit new page set chart and fix bugs profil metrics

comit new page set chart and fix bugs profil metrics

---

webapps/assets/core/dealprofilmetrics.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/turnaroundtime.html

set css design and implement select quick info

set css design and implement select quick info

---

webapps/assets/core/dashboard-dealprofilmetrics.js
webapps/views/dashboard/dealprofilmetrics.html

fixed deal profil metrics

---

webapps/assets/core/dashboard-compare-contrast.js
webapps/assets/core/dashboard-conversionrate.js
webapps/controllers/dashboard.go
webapps/views/dashboard/compare_contrast.html
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/turnaroundtime.html

fix filter pop up

---

webapps/controllers/dashboard.go
webapps/models/accountdetails.go

Deal profile metric have special Deal Status filter that doesn't appear
on the other page. We start by introducing custom filter that can be
enabled per page.

Prepare for deal profile metric - only - dashboard filter.

---

webapps/assets/core/turnaroundtime.js
webapps/controllers/dashboard.go
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/turnaroundtime.html

At least now working. Next step is implement data amount and count for proper bar chart.

Implement tat trend group by region

---

webapps/assets/core/dashboard-compare-contrast.js
webapps/assets/core/dashboard-conversionrate.js
webapps/controllers/dashboard.go
webapps/views/dashboard/compare_contrast.html
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/turnaroundtime.html

fix layout pop up

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html

fixing chart convertion rate

---

webapps/assets/core/dashboard-dealprofilmetrics.js
webapps/controllers/dashboard.go
webapps/views/dashboard/dealprofilmetrics.html

added trend metric for region option

trend mteric

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html

layouting conversion rate 

---

webapps/assets/core/dashboard-conversionrate.js
webapps/controllers/dashboard.go
webapps/views/dashboard/conversionrate.html

comit fix quick info

---

webapps/assets/core/dashboard-compare-contrast.js
webapps/views/dashboard/compare_contrast.html
webapps/views/dashboard/turnaroundtime.html

comit ui pop up

---

webapps/assets/core/dashboard-conversionrate.js
webapps/controllers/dashboard.go

ui implement conversion

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html

comit review 1 convertion

---

webapps/assets/core/dashboard-conversionrate.js
webapps/controllers/dashboard.go

comit value funnel

---

webapps/views/_layout.html

fix menu ui when  side bar open or close

fix menu ui when  side bar open or close

---

webapps/assets/core/layout.js
webapps/controllers/dashboard.go
webapps/views/_layout.html
webapps/views/dashboard/default.html

menu filter snapshot tat

---

webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/time_tracker.html

fix layout panel

---

webapps/controllers/dashboard.go
webapps/views/dashboard/default.html
webapps/views/shared/filter_menu.html

fix height filter on alert & summary

fix height filter on alert & summary

---

webapps/assets/core/dashboard-time-tracker.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/time_tracker.html
webapps/views/dashboard/turnaroundtime.html
webapps/views/shared/filter_menu.html

tat & alert update done

---

webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/dashboard-dashfilter.js
webapps/assets/core/dashboard-dealprofilmetrics.js
webapps/assets/core/dashboard-time-tracker.js
webapps/assets/core/dashboard.js
webapps/assets/core/turnaroundtime.js
webapps/controllers/dashboard.go
webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/default.html
webapps/views/dashboard/time_tracker.html
webapps/views/dashboard/turnaroundtime.html
webapps/views/shared/filter_menu.html

fix filter other page and fix screen width adjustment

fix filter other page

---

webapps/views/shared/filter_menu.html

fix style sidebar filter

---

webapps/assets/core/dashboard-alert-summary.js
webapps/assets/core/dashboard-time-tracker.js
webapps/views/dashboard/alert_summary.html

set chart quick info alert sumary

set chart quick info alert sumary

---

webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/dashboard-dealprofilmetrics.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/turnaroundtime.html

fix chart and labels

---

webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/turnaroundtime.js
webapps/assets/img/aicon/actioned.svg
webapps/assets/img/aicon/analized.svg
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/turnaroundtime.html

add arrows at conversion page

---

webapps/assets/core/dashboard-compare-contrast.js
webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/role-setting.js
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/dashboard/turnaroundtime.html

comit change chart label and icon

comit change chart label and icon

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html

set arrow update

---

webapps/assets/core/dashboard-alert-summary.js
webapps/views/dashboard/time_tracker.html

fix label and resize image

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/time_tracker.html

set footnote and fix coloumn layout

set footnote and fix coloumn layout

---

webapps/assets/core/dashboard-alert-summary.js
webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/dashboard-time-tracker.js
webapps/assets/core/dashboard.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/time_tracker.html
webapps/views/dashboard/turnaroundtime.html

quick info

---

webapps/assets/core/dashboard-alert-summary.js
webapps/assets/core/dashboard-conversionrate.js
webapps/assets/core/turnaroundtime.js
webapps/views/dashboard/alert_summary.html
webapps/views/dashboard/conversionrate.html
webapps/views/dashboard/time_tracker.html
webapps/views/dashboard/turnaroundtime.html

alert and updates number quick info layouting

alert and updates

---

webapps/assets/core/dashboard-conversionrate.js
webapps/views/dashboard/conversionrate.html

funnel tittle

---

webapps/assets/core/dashboard-dealprofilmetrics.js
webapps/views/creditscorecard/form.html
webapps/views/dashboard/dealprofilmetrics.html
webapps/views/datacapturing/cibil.html
webapps/views/datacapturing/cibilnew.html
webapps/views/datacapturing/entryreportcibil.html
webapps/views/datacapturing/financialinformation.html
webapps/views/duediligence/master.html
webapps/views/financialsnapshot/kiri.html

comit Date.now()
